# VEDA AI/ML Internship – Day 18

## Task 18: Select Dataset Columns

### Objective
Learn how to access and select specific rows and columns from a Pandas DataFrame using `loc` and `iloc`.

### Tools Used
- Python
- Pandas
- Jupyter Notebook

### Dataset
Iris Dataset

## 1. Import Pandas

Pandas is a Python library used for data manipulation and analysis.

In [1]:
import pandas as pd

## 2. Load the Iris Dataset

The Iris dataset contains measurements of iris flowers.

It has the following features:
- Sepal Length
- Sepal Width
- Petal Length
- Petal Width
- Species

In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

columns = [
    "sepal_length",
    "sepal_width",
    "petal_length",
    "petal_width",
    "species"
]

df = pd.read_csv(url, names=columns)

df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

## 3. Explore the Dataset

First, we check the shape and column names of the DataFrame.

In [3]:
print("Dataset Shape:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

Dataset Shape: (150, 5)

Column Names:
['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

## 4. Select a Single Column Using `loc`

The `loc` accessor is label-based.

The following code selects the `sepal_length` column from all rows.

In [4]:
df.loc[:, "sepal_length"]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

## 5. Select Multiple Columns Using `loc`

Multiple columns can be selected by providing their column names inside a list.

In [5]:
df.loc[:, ["sepal_length", "petal_length", "species"]]

     sepal_length  petal_length         species
0             5.1           1.4     Iris-setosa
1             4.9           1.4     Iris-setosa
2             4.7           1.3     Iris-setosa
3             4.6           1.5     Iris-setosa
4             5.0           1.4     Iris-setosa
..            ...           ...             ...
145           6.7           5.2  Iris-virginica
146           6.3           5.0  Iris-virginica
147           6.5           5.2  Iris-virginica
148           6.2           5.4  Iris-virginica
149           5.9           5.1  Iris-virginica

[150 rows x 3 columns]

## 6. Select Specific Rows and Columns Using `loc`

`loc` can be used to select both specific rows and specific columns.

Here, we select rows 0 to 4 and three columns:
- Sepal Length
- Petal Length
- Species

In [6]:
df.loc[0:4, ["sepal_length", "petal_length", "species"]]

   sepal_length  petal_length      species
0           5.1           1.4  Iris-setosa
1           4.9           1.4  Iris-setosa
2           4.7           1.3  Iris-setosa
3           4.6           1.5  Iris-setosa
4           5.0           1.4  Iris-setosa

## 7. Select a Single Column Using `iloc`

The `iloc` accessor is position-based.

The following code selects the first column using its integer position `0`.

In [8]:
df.iloc[:, 0]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

## 8. Select Multiple Columns Using `iloc`

We can select multiple columns by specifying their integer positions.

Column positions:
- 0 → sepal_length
- 1 → sepal_width
- 2 → petal_length
- 3 → petal_width
- 4 → species

In [9]:
df.iloc[:, [0, 2, 4]]

     sepal_length  petal_length         species
0             5.1           1.4     Iris-setosa
1             4.9           1.4     Iris-setosa
2             4.7           1.3     Iris-setosa
3             4.6           1.5     Iris-setosa
4             5.0           1.4     Iris-setosa
..            ...           ...             ...
145           6.7           5.2  Iris-virginica
146           6.3           5.0  Iris-virginica
147           6.5           5.2  Iris-virginica
148           6.2           5.4  Iris-virginica
149           5.9           5.1  Iris-virginica

[150 rows x 3 columns]

## 9. Select Specific Rows and Columns Using `iloc`

The following code selects the first five rows and columns at positions 0, 2, and 4.

In [10]:
df.iloc[0:5, [0, 2, 4]]

   sepal_length  petal_length      species
0           5.1           1.4  Iris-setosa
1           4.9           1.4  Iris-setosa
2           4.7           1.3  Iris-setosa
3           4.6           1.5  Iris-setosa
4           5.0           1.4  Iris-setosa

## 10. Difference Between `loc` and `iloc`

| Method | Selection Type | Example |
|---|---|---|
| `loc` | Label-based | `df.loc[:, "sepal_length"]` |
| `iloc` | Integer position-based | `df.iloc[:, 0]` |

### Key Difference

- `loc` uses row and column labels.
- `iloc` uses integer positions.
- `loc` is useful when working with meaningful labels.
- `iloc` is useful when selecting data based on its position.

## 11. Select Final Records

Now we select the first 10 records and three specific columns using `loc`.

In [11]:
selected_data = df.loc[
    0:9,
    ["sepal_length", "petal_width", "species"]
]

selected_data

   sepal_length  petal_width      species
0           5.1          0.2  Iris-setosa
1           4.9          0.2  Iris-setosa
2           4.7          0.2  Iris-setosa
3           4.6          0.2  Iris-setosa
4           5.0          0.2  Iris-setosa
5           5.4          0.4  Iris-setosa
6           4.6          0.3  Iris-setosa
7           5.0          0.2  Iris-setosa
8           4.4          0.2  Iris-setosa
9           4.9          0.1  Iris-setosa